2022/09/22 12:31:01 - Terminal_Log - INFO      - log_save.py : 22 line - run the section pre_step
2022/09/22 12:31:02 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization
2022/09/22 12:31:02 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:31:02 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:02 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/imgs
2022/09/22 12:31:03 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:31:03 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:03 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/tools
2022/09/22 12:31:03 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:31:03 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:04 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/vt_sut_linux_tools
2022/09/22 12:31:04 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:31:04 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:04 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/virtualization_inband
2022/09/22 12:31:05 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:31:05 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:05 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; rm -rf /usr/bin/python; ln -s /usr/bin/python3.6 /usr/bin/python
2022/09/22 12:31:05 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:31:05 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:06 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; rm -rf /usr/bin/pip;ln -s /usr/bin/pip3.6 /usr/bin/pip
2022/09/22 12:31:06 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:31:06 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:07 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; python -m pip install --upgrade pip
2022/09/22 12:31:08 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages (21.3.1)
 

2022/09/22 12:31:08 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:31:08 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /etc/yum.repos.d/repos.bak; mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/repos.bak
2022/09/22 12:31:09 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:31:09 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:09 - Terminal_Log - INFO      - log_save.py : 22 line - cp ../FILES/Centos-8.repo to /etc/yum.repos.d/Centos-8.repo
2022/09/22 12:31:10 - Terminal_Log - INFO      - log_save.py : 22 line - cp done

2022/09/22 12:31:10 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum update -y
2022/09/22 12:31:14 - Terminal_Log - INFO      - log_save.py : 22 line - out: CentOS-8 - Base                                 5.0 kB/s | 3.9 kB     00:00    
CentOS-8 - AppStream                            6.2 kB/s | 4.3 kB     00:00    
CentOS-8 Extra Packages - x86_64                4.0 kB/s | 4.7 kB     00:01    
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:31:14 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:14 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: yum remove qemu-kvm -y
2022/09/22 12:31:15 - Terminal_Log - INFO      - log_save.py : 22 line - out: No match for argument: qemu-kvm
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:31:15 - Terminal_Log - ERROR     - log_save.py : 28 line - err: No packages marked for removal.
 

2022/09/22 12:31:16 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install libvirt -y
2022/09/22 12:31:17 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:02 ago on Thu 22 Sep 2022 03:00:24 AM IST.
Package libvirt-8.0.0-6.module_el8.7.0+1140+ff0772f9.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:31:17 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:17 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install python3-libvirt -y
2022/09/22 12:31:18 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:04 ago on Thu 22 Sep 2022 03:00:24 AM IST.
Package python3-libvirt-6.0.0-1.module_el8.5.0+746+bbd5d70c.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:31:18 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:18 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install virt-install -y
2022/09/22 12:31:20 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:05 ago on Thu 22 Sep 2022 03:00:24 AM IST.
Package virt-install-2.2.1-4.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:31:20 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:20 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install iperf -y
2022/09/22 12:31:21 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:07 ago on Thu 22 Sep 2022 03:00:24 AM IST.
Package iperf-2.1.6-2.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:31:21 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:21 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install wget -y
2022/09/22 12:31:22 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:08 ago on Thu 22 Sep 2022 03:00:24 AM IST.
Package wget-1.19.5-10.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:31:22 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:23 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install virt-manager -y
2022/09/22 12:31:24 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:10 ago on Thu 22 Sep 2022 03:00:24 AM IST.
Package virt-manager-2.2.1-4.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:31:24 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:24 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install tigervnc -y
2022/09/22 12:31:25 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:11 ago on Thu 22 Sep 2022 03:00:24 AM IST.
Package tigervnc-1.11.0-9.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:31:25 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:26 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install systemd-devel -y
2022/09/22 12:31:27 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:13 ago on Thu 22 Sep 2022 03:00:24 AM IST.
Package systemd-devel-239-51.el8_5.2.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:31:27 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:27 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install rpm-build autoconf automake libtool pkgconf rpmdevtools -y
2022/09/22 12:31:28 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:14 ago on Thu 22 Sep 2022 03:00:24 AM IST.
Package rpm-build-4.14.3-23.el8.x86_64 is already installed.
Package autoconf-2.69-29.el8.noarch is already installed.
Package automake-1.16.1-7.el8.noarch is already installed.
Package libtool-2.4.6-25.el8.x86_64 is already installed.
Package pkgconf-1.4.2-1.el8.x86_64 is already installed.
Package rpmdevtools-8.10-8.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:31:28 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:29 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install asciidoc xmlto libuuid-devel json-c-devel kmod-devel libudev-devel -y
2022/09/22 12:31:30 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:15 ago on Thu 22 Sep 2022 03:00:24 AM IST.
Package asciidoc-8.6.10-0.5.20180627gitf7c2274.el8.noarch is already installed.
No match for argument: kmod-devel
Package systemd-devel-239-51.el8_5.2.x86_64 is already installed.
 

2022/09/22 12:31:30 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: kmod-devel
 

2022/09/22 12:31:30 - Terminal_Log - INFO      - log_save.py : 22 line - run the section python_env_step
2022/09/22 12:31:30 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install gcc-c++ -y
2022/09/22 12:31:31 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:17 ago on Thu 22 Sep 2022 03:00:24 AM IST.
Package gcc-c++-8.5.0-13.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:31:31 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:32 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install rust -y
2022/09/22 12:31:33 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:18 ago on Thu 22 Sep 2022 03:00:24 AM IST.
Package rust-1.54.0-3.module_el8.5.0+1023+0c63d3d6.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:31:33 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:33 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install python36-devel -y
2022/09/22 12:31:34 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:20 ago on Thu 22 Sep 2022 03:00:24 AM IST.
Package python36-devel-3.6.8-38.module_el8.5.0+895+a459eca8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:31:34 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:31:34 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install xmltodict  -i https://pypi.org/simple--user
2022/09/22 12:31:35 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: xmltodict in /usr/local/lib/python3.6/site-packages (0.13.0)
 

2022/09/22 12:31:35 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:31:35 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install wcwidth  -i https://pypi.org/simple--user
2022/09/22 12:31:36 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (0.2.5)
 

2022/09/22 12:31:36 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:31:36 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install pathlib2  -i https://pypi.org/simple--user
2022/09/22 12:31:37 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: pathlib2 in /usr/local/lib/python3.6/site-packages (2.3.7.post1)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from pathlib2) (1.11.0)
 

2022/09/22 12:31:37 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:31:38 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install artifactory  -i https://pypi.org/simple--user
2022/09/22 12:31:38 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: artifactory in /usr/local/lib/python3.6/site-packages (0.1.17)
Requirement already satisfied: pathlib in /usr/local/lib/python3.6/site-packages (from artifactory) (1.0.1)
Requirement already satisfied: requests in /usr/lib/python3.6/site-packages (from artifactory) (2.20.0)
Requirement already satisfied: python-dateutil in /usr/lib/python3.6/site-packages (from artifactory) (2.6.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.6/site-packages (from python-dateutil->artifactory) (1.11.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests->artifactory) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/lib/python3.6/site-packages (from requests->artifactory) (2.5)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests->artifactory) (1.24.2)
 

2022/09/22 12:31:38 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:31:39 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install anybadge  -i https://pypi.org/simple--user
2022/09/22 12:31:39 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: anybadge in /usr/local/lib/python3.6/site-packages (1.9.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from anybadge) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.6/site-packages (from packaging->anybadge) (3.0.9)
 

2022/09/22 12:31:39 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:31:40 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install pyqt5  -i https://pypi.org/simple--user
2022/09/22 12:31:40 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: pyqt5 in /usr/local/lib64/python3.6/site-packages (5.15.6)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /usr/local/lib64/python3.6/site-packages (from pyqt5) (12.9.1)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in /usr/local/lib64/python3.6/site-packages (from pyqt5) (5.15.2)
 

2022/09/22 12:31:40 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:31:41 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install pywin32  -i https://pypi.org/simple--user
2022/09/22 12:31:42 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
 

2022/09/22 12:31:42 - Terminal_Log - ERROR     - log_save.py : 28 line - err: ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32
 

2022/09/22 12:31:43 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install prettytable  -i https://pypi.org/simple--user
2022/09/22 12:31:44 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: prettytable in /usr/local/lib/python3.6/site-packages (2.5.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (from prettytable) (0.2.5)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.6/site-packages (from prettytable) (4.8.3)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/site-packages (from importlib-metadata->prettytable) (3.6.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.6/site-packages (from importlib-metadata->prettytable) (4.1.1)
 

2022/09/22 12:31:44 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:31:44 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install bcrypt  -i https://pypi.org/simple--user
2022/09/22 12:31:45 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: bcrypt in /usr/local/lib64/python3.6/site-packages (4.0.0)
 

2022/09/22 12:31:45 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:31:45 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install setuptools_rust  -i https://pypi.org/simple--user
2022/09/22 12:31:46 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: setuptools_rust in /usr/local/lib/python3.6/site-packages (1.1.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.6/site-packages (from setuptools_rust) (4.1.1)
Requirement already satisfied: setuptools>=46.1 in /usr/local/lib/python3.6/site-packages (from setuptools_rust) (59.6.0)
Requirement already satisfied: semantic-version<3,>=2.8.2 in /usr/local/lib/python3.6/site-packages (from setuptools_rust) (2.10.0)
 

2022/09/22 12:31:46 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:31:46 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install cffi  -i https://pypi.org/simple--user
2022/09/22 12:31:47 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: cffi in /usr/local/lib64/python3.6/site-packages (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi) (2.21)
 

2022/09/22 12:31:47 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:31:47 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install cryptography  -i https://pypi.org/simple--user
2022/09/22 12:31:48 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: cryptography in /usr/local/lib64/python3.6/site-packages (38.0.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib64/python3.6/site-packages (from cryptography) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.12->cryptography) (2.21)
 

2022/09/22 12:31:48 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:31:48 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install prettytable  -i https://pypi.org/simple--user
2022/09/22 12:31:49 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: prettytable in /usr/local/lib/python3.6/site-packages (2.5.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.6/site-packages (from prettytable) (4.8.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (from prettytable) (0.2.5)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.6/site-packages (from importlib-metadata->prettytable) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/site-packages (from importlib-metadata->prettytable) (3.6.0)
 

2022/09/22 12:31:49 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:31:49 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install pynacl  -i https://pypi.org/simple--user
2022/09/22 12:31:50 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: pynacl in /usr/local/lib64/python3.6/site-packages/PyNaCl-1.5.0-py3.6-linux-x86_64.egg (1.5.0)
Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib64/python3.6/site-packages (from pynacl) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.4.1->pynacl) (2.21)
 

2022/09/22 12:31:50 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:31:51 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install paramiko  -i https://pypi.org/simple--user
2022/09/22 12:31:51 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: paramiko in /usr/local/lib/python3.6/site-packages (2.11.0)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib64/python3.6/site-packages (from paramiko) (4.0.0)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib64/python3.6/site-packages/PyNaCl-1.5.0-py3.6-linux-x86_64.egg (from paramiko) (1.5.0)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from paramiko) (1.11.0)
Requirement already satisfied: cryptography>=2.5 in /usr/local/lib64/python3.6/site-packages (from paramiko) (38.0.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib64/python3.6/site-packages (from cryptography>=2.5->paramiko) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.12->cryptography>=2.5->paramiko) (2.21)
 

2022/09/22 12:31:51 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:31:52 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install scp  -i https://pypi.org/simple--user
2022/09/22 12:31:52 - Terminal_Log - INFO      - log_save.py : 22 line - out: Looking in indexes: https://pypi.org/simple--user
Requirement already satisfied: scp in /usr/local/lib/python3.6/site-packages (0.14.4)
Requirement already satisfied: paramiko in /usr/local/lib/python3.6/site-packages (from scp) (2.11.0)
Requirement already satisfied: cryptography>=2.5 in /usr/local/lib64/python3.6/site-packages (from paramiko->scp) (38.0.1)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib64/python3.6/site-packages/PyNaCl-1.5.0-py3.6-linux-x86_64.egg (from paramiko->scp) (1.5.0)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from paramiko->scp) (1.11.0)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib64/python3.6/site-packages (from paramiko->scp) (4.0.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib64/python3.6/site-packages (from cryptography>=2.5->paramiko->scp) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.12->cryptography>=2.5->paramiko->scp) (2.21)
 

2022/09/22 12:31:52 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

