2022/09/22 12:26:40 - Terminal_Log - INFO      - log_save.py : 22 line - run the section pre_step
2022/09/22 12:26:40 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   mkdir -p /home/BKCPkg/domains/virtualization
2022/09/22 12:26:40 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:26:40 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:26:41 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   mkdir -p /home/BKCPkg/domains/virtualization/imgs
2022/09/22 12:26:41 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:26:41 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:26:41 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   mkdir -p /home/BKCPkg/domains/virtualization/tools
2022/09/22 12:26:42 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:26:42 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:26:42 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   mkdir -p /home/BKCPkg/domains/virtualization/vt_sut_linux_tools
2022/09/22 12:26:42 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:26:42 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:26:43 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   mkdir -p /home/BKCPkg/domains/virtualization/virtualization_inband
2022/09/22 12:26:43 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:26:43 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:26:44 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   rm -rf /usr/bin/python; ln -s /usr/bin/python3.6 /usr/bin/python
2022/09/22 12:26:44 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:26:44 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:26:44 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   rm -rf /usr/bin/pip;ln -s /usr/bin/pip3.6 /usr/bin/pip
2022/09/22 12:26:44 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:26:44 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:26:45 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;; python -m pip install --upgrade pip
2022/09/22 12:26:45 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:26:45 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;;'
bash: -c: line 0: `  export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;; python -m pip install --upgrade pip'
 

2022/09/22 12:26:46 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   mkdir -p /etc/yum.repos.d/repos.bak; mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/repos.bak
2022/09/22 12:26:46 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:26:46 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:26:47 - Terminal_Log - INFO      - log_save.py : 22 line - cp ../FILES/Centos-8.repo to /etc/yum.repos.d/Centos-8.repo
2022/09/22 12:26:47 - Terminal_Log - INFO      - log_save.py : 22 line - cp done

2022/09/22 12:26:47 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum update -y
2022/09/22 12:26:52 - Terminal_Log - INFO      - log_save.py : 22 line - out: CentOS-8 - Base                                 3.0 kB/s | 3.9 kB     00:01    
CentOS-8 - AppStream                            4.6 kB/s | 4.3 kB     00:00    
CentOS-8 Extra Packages - x86_64                3.5 kB/s | 4.7 kB     00:01    
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:26:52 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:26:52 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: yum remove qemu-kvm -y
2022/09/22 12:26:53 - Terminal_Log - INFO      - log_save.py : 22 line - out: No match for argument: qemu-kvm
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:26:53 - Terminal_Log - ERROR     - log_save.py : 28 line - err: No packages marked for removal.
 

2022/09/22 12:26:54 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install libvirt -y
2022/09/22 12:26:55 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:02 ago on Thu 22 Sep 2022 02:56:02 AM IST.
Package libvirt-8.0.0-6.module_el8.7.0+1140+ff0772f9.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:26:55 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:26:55 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install python3-libvirt -y
2022/09/22 12:26:56 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:04 ago on Thu 22 Sep 2022 02:56:02 AM IST.
Package python3-libvirt-6.0.0-1.module_el8.5.0+746+bbd5d70c.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:26:56 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:26:56 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install virt-install -y
2022/09/22 12:26:57 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:05 ago on Thu 22 Sep 2022 02:56:02 AM IST.
Package virt-install-2.2.1-4.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:26:57 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:26:58 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install iperf -y
2022/09/22 12:26:59 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:07 ago on Thu 22 Sep 2022 02:56:02 AM IST.
Package iperf-2.1.6-2.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:26:59 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:26:59 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install wget -y
2022/09/22 12:27:00 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:08 ago on Thu 22 Sep 2022 02:56:02 AM IST.
Package wget-1.19.5-10.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:27:00 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:27:01 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install virt-manager -y
2022/09/22 12:27:02 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:10 ago on Thu 22 Sep 2022 02:56:02 AM IST.
Package virt-manager-2.2.1-4.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:27:02 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:27:02 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install tigervnc -y
2022/09/22 12:27:03 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:11 ago on Thu 22 Sep 2022 02:56:02 AM IST.
Package tigervnc-1.11.0-9.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:27:03 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:27:04 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install systemd-devel -y
2022/09/22 12:27:05 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:12 ago on Thu 22 Sep 2022 02:56:02 AM IST.
Package systemd-devel-239-51.el8_5.2.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:27:05 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:27:05 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install rpm-build autoconf automake libtool pkgconf rpmdevtools -y
2022/09/22 12:27:06 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:14 ago on Thu 22 Sep 2022 02:56:02 AM IST.
Package rpm-build-4.14.3-23.el8.x86_64 is already installed.
Package autoconf-2.69-29.el8.noarch is already installed.
Package automake-1.16.1-7.el8.noarch is already installed.
Package libtool-2.4.6-25.el8.x86_64 is already installed.
Package pkgconf-1.4.2-1.el8.x86_64 is already installed.
Package rpmdevtools-8.10-8.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:27:06 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:27:07 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install asciidoc xmlto libuuid-devel json-c-devel kmod-devel libudev-devel -y
2022/09/22 12:27:08 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:15 ago on Thu 22 Sep 2022 02:56:02 AM IST.
Package asciidoc-8.6.10-0.5.20180627gitf7c2274.el8.noarch is already installed.
No match for argument: kmod-devel
Package systemd-devel-239-51.el8_5.2.x86_64 is already installed.
 

2022/09/22 12:27:08 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: kmod-devel
 

2022/09/22 12:27:08 - Terminal_Log - INFO      - log_save.py : 22 line - run the section python_env_step
2022/09/22 12:27:08 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install gcc-c++ -y
2022/09/22 12:27:09 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:17 ago on Thu 22 Sep 2022 02:56:02 AM IST.
Package gcc-c++-8.5.0-13.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:27:09 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:27:09 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install rust -y
2022/09/22 12:27:10 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:18 ago on Thu 22 Sep 2022 02:56:02 AM IST.
Package rust-1.54.0-3.module_el8.5.0+1023+0c63d3d6.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:27:10 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:27:11 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install python36-devel -y
2022/09/22 12:27:12 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:20 ago on Thu 22 Sep 2022 02:56:02 AM IST.
Package python36-devel-3.6.8-38.module_el8.5.0+895+a459eca8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:27:12 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:27:12 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   pip install xmltodict  
2022/09/22 12:27:13 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: xmltodict in /usr/local/lib/python3.6/site-packages (0.13.0)
 

2022/09/22 12:27:13 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:27:13 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   pip install wcwidth  
2022/09/22 12:27:14 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (0.2.5)
 

2022/09/22 12:27:14 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:27:15 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   pip install pathlib2  
2022/09/22 12:27:15 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: pathlib2 in /usr/local/lib/python3.6/site-packages (2.3.7.post1)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from pathlib2) (1.11.0)
 

2022/09/22 12:27:15 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:27:16 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   pip install artifactory  
2022/09/22 12:27:16 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: artifactory in /usr/local/lib/python3.6/site-packages (0.1.17)
Requirement already satisfied: pathlib in /usr/local/lib/python3.6/site-packages (from artifactory) (1.0.1)
Requirement already satisfied: requests in /usr/lib/python3.6/site-packages (from artifactory) (2.20.0)
Requirement already satisfied: python-dateutil in /usr/lib/python3.6/site-packages (from artifactory) (2.6.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.6/site-packages (from python-dateutil->artifactory) (1.11.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests->artifactory) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/lib/python3.6/site-packages (from requests->artifactory) (2.5)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests->artifactory) (1.24.2)
 

2022/09/22 12:27:16 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:27:17 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   pip install anybadge  
2022/09/22 12:27:17 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: anybadge in /usr/local/lib/python3.6/site-packages (1.9.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from anybadge) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.6/site-packages (from packaging->anybadge) (3.0.9)
 

2022/09/22 12:27:17 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:27:18 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   pip install pyqt5  
2022/09/22 12:27:18 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: pyqt5 in /usr/local/lib64/python3.6/site-packages (5.15.6)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in /usr/local/lib64/python3.6/site-packages (from pyqt5) (5.15.2)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /usr/local/lib64/python3.6/site-packages (from pyqt5) (12.9.1)
 

2022/09/22 12:27:18 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:27:19 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   pip install pywin32  
2022/09/22 12:29:40 - Terminal_Log - INFO      - log_save.py : 22 line - run the section pre_step
2022/09/22 12:29:40 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization
2022/09/22 12:29:40 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:29:40 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:29:41 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/imgs
2022/09/22 12:29:41 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:29:41 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:29:41 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/tools
2022/09/22 12:29:42 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:29:42 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:29:42 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/vt_sut_linux_tools
2022/09/22 12:29:42 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:29:42 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:29:43 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/virtualization_inband
2022/09/22 12:29:43 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:29:43 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:29:44 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; rm -rf /usr/bin/python; ln -s /usr/bin/python3.6 /usr/bin/python
2022/09/22 12:29:44 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:29:44 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:29:44 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; rm -rf /usr/bin/pip;ln -s /usr/bin/pip3.6 /usr/bin/pip
2022/09/22 12:29:44 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:29:44 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:29:45 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; python -m pip install --upgrade pip
2022/09/22 12:29:46 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages (21.3.1)
 

2022/09/22 12:29:46 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:29:47 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /etc/yum.repos.d/repos.bak; mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/repos.bak
2022/09/22 12:29:47 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:29:47 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:29:48 - Terminal_Log - INFO      - log_save.py : 22 line - cp ../FILES/Centos-8.repo to /etc/yum.repos.d/Centos-8.repo
2022/09/22 12:29:48 - Terminal_Log - INFO      - log_save.py : 22 line - cp done

2022/09/22 12:29:49 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum update -y
2022/09/22 12:29:53 - Terminal_Log - INFO      - log_save.py : 22 line - out: CentOS-8 - Base                                 3.0 kB/s | 3.9 kB     00:01    
CentOS-8 - AppStream                            4.8 kB/s | 4.3 kB     00:00    
CentOS-8 Extra Packages - x86_64                3.9 kB/s | 4.7 kB     00:01    
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:29:53 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:29:53 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: yum remove qemu-kvm -y
2022/09/22 12:29:54 - Terminal_Log - INFO      - log_save.py : 22 line - out: No match for argument: qemu-kvm
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:29:54 - Terminal_Log - ERROR     - log_save.py : 28 line - err: No packages marked for removal.
 

2022/09/22 12:29:55 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install libvirt -y
2022/09/22 12:29:56 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:03 ago on Thu 22 Sep 2022 02:59:03 AM IST.
Package libvirt-8.0.0-6.module_el8.7.0+1140+ff0772f9.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:29:56 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:29:56 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install python3-libvirt -y
2022/09/22 12:29:57 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:04 ago on Thu 22 Sep 2022 02:59:03 AM IST.
Package python3-libvirt-6.0.0-1.module_el8.5.0+746+bbd5d70c.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:29:57 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:29:58 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install virt-install -y
2022/09/22 12:29:59 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:05 ago on Thu 22 Sep 2022 02:59:03 AM IST.
Package virt-install-2.2.1-4.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:29:59 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:29:59 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install iperf -y
2022/09/22 12:30:00 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:07 ago on Thu 22 Sep 2022 02:59:03 AM IST.
Package iperf-2.1.6-2.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:30:00 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:30:00 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install wget -y
2022/09/22 12:30:01 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:08 ago on Thu 22 Sep 2022 02:59:03 AM IST.
Package wget-1.19.5-10.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:30:01 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:30:02 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install virt-manager -y
2022/09/22 12:30:03 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:10 ago on Thu 22 Sep 2022 02:59:03 AM IST.
Package virt-manager-2.2.1-4.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:30:03 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:30:03 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install tigervnc -y
2022/09/22 12:30:04 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:11 ago on Thu 22 Sep 2022 02:59:03 AM IST.
Package tigervnc-1.11.0-9.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:30:04 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:30:05 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install systemd-devel -y
2022/09/22 12:30:06 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:13 ago on Thu 22 Sep 2022 02:59:03 AM IST.
Package systemd-devel-239-51.el8_5.2.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:30:06 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:30:06 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install rpm-build autoconf automake libtool pkgconf rpmdevtools -y
2022/09/22 12:30:07 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:14 ago on Thu 22 Sep 2022 02:59:03 AM IST.
Package rpm-build-4.14.3-23.el8.x86_64 is already installed.
Package autoconf-2.69-29.el8.noarch is already installed.
Package automake-1.16.1-7.el8.noarch is already installed.
Package libtool-2.4.6-25.el8.x86_64 is already installed.
Package pkgconf-1.4.2-1.el8.x86_64 is already installed.
Package rpmdevtools-8.10-8.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:30:07 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:30:08 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install asciidoc xmlto libuuid-devel json-c-devel kmod-devel libudev-devel -y
2022/09/22 12:30:09 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:16 ago on Thu 22 Sep 2022 02:59:03 AM IST.
Package asciidoc-8.6.10-0.5.20180627gitf7c2274.el8.noarch is already installed.
No match for argument: kmod-devel
Package systemd-devel-239-51.el8_5.2.x86_64 is already installed.
 

2022/09/22 12:30:09 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: kmod-devel
 

2022/09/22 12:30:09 - Terminal_Log - INFO      - log_save.py : 22 line - run the section python_env_step
2022/09/22 12:30:09 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install gcc-c++ -y
2022/09/22 12:30:10 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:17 ago on Thu 22 Sep 2022 02:59:03 AM IST.
Package gcc-c++-8.5.0-13.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:30:10 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:30:11 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install rust -y
2022/09/22 12:30:12 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:18 ago on Thu 22 Sep 2022 02:59:03 AM IST.
Package rust-1.54.0-3.module_el8.5.0+1023+0c63d3d6.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:30:12 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:30:12 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum install python36-devel -y
2022/09/22 12:30:13 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:20 ago on Thu 22 Sep 2022 02:59:03 AM IST.
Package python36-devel-3.6.8-38.module_el8.5.0+895+a459eca8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:30:13 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:30:13 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install xmltodict  -i https://pypi.org/simple
2022/09/22 12:30:14 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: xmltodict in /usr/local/lib/python3.6/site-packages (0.13.0)
 

2022/09/22 12:30:14 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:30:15 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install wcwidth  -i https://pypi.org/simple
2022/09/22 12:30:15 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (0.2.5)
 

2022/09/22 12:30:15 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:30:16 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install pathlib2  -i https://pypi.org/simple
2022/09/22 12:30:16 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: pathlib2 in /usr/local/lib/python3.6/site-packages (2.3.7.post1)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from pathlib2) (1.11.0)
 

2022/09/22 12:30:16 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:30:17 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install artifactory  -i https://pypi.org/simple
2022/09/22 12:30:17 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: artifactory in /usr/local/lib/python3.6/site-packages (0.1.17)
Requirement already satisfied: pathlib in /usr/local/lib/python3.6/site-packages (from artifactory) (1.0.1)
Requirement already satisfied: requests in /usr/lib/python3.6/site-packages (from artifactory) (2.20.0)
Requirement already satisfied: python-dateutil in /usr/lib/python3.6/site-packages (from artifactory) (2.6.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.6/site-packages (from python-dateutil->artifactory) (1.11.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests->artifactory) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/lib/python3.6/site-packages (from requests->artifactory) (2.5)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests->artifactory) (1.24.2)
 

2022/09/22 12:30:17 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:30:18 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install anybadge  -i https://pypi.org/simple
2022/09/22 12:30:18 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: anybadge in /usr/local/lib/python3.6/site-packages (1.9.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from anybadge) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.6/site-packages (from packaging->anybadge) (3.0.9)
 

2022/09/22 12:30:18 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:30:19 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install pyqt5  -i https://pypi.org/simple
2022/09/22 12:30:19 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: pyqt5 in /usr/local/lib64/python3.6/site-packages (5.15.6)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /usr/local/lib64/python3.6/site-packages (from pyqt5) (12.9.1)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in /usr/local/lib64/python3.6/site-packages (from pyqt5) (5.15.2)
 

2022/09/22 12:30:19 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:30:20 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install pywin32  -i https://pypi.org/simple
2022/09/22 12:30:22 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:30:22 - Terminal_Log - ERROR     - log_save.py : 28 line - err: ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32
 

2022/09/22 12:30:22 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install prettytable  -i https://pypi.org/simple
2022/09/22 12:30:23 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: prettytable in /usr/local/lib/python3.6/site-packages (2.5.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.6/site-packages (from prettytable) (4.8.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (from prettytable) (0.2.5)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.6/site-packages (from importlib-metadata->prettytable) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/site-packages (from importlib-metadata->prettytable) (3.6.0)
 

2022/09/22 12:30:23 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:30:23 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install bcrypt  -i https://pypi.org/simple
2022/09/22 12:30:24 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: bcrypt in /usr/local/lib64/python3.6/site-packages (4.0.0)
 

2022/09/22 12:30:24 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:30:24 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install setuptools_rust  -i https://pypi.org/simple
2022/09/22 12:30:25 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: setuptools_rust in /usr/local/lib/python3.6/site-packages (1.1.2)
Requirement already satisfied: setuptools>=46.1 in /usr/local/lib/python3.6/site-packages (from setuptools_rust) (59.6.0)
Requirement already satisfied: semantic-version<3,>=2.8.2 in /usr/local/lib/python3.6/site-packages (from setuptools_rust) (2.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.6/site-packages (from setuptools_rust) (4.1.1)
 

2022/09/22 12:30:25 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:30:25 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install cffi  -i https://pypi.org/simple
2022/09/22 12:30:26 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: cffi in /usr/local/lib64/python3.6/site-packages (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi) (2.21)
 

2022/09/22 12:30:26 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:30:26 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install cryptography  -i https://pypi.org/simple
2022/09/22 12:30:27 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: cryptography in /usr/local/lib64/python3.6/site-packages (38.0.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib64/python3.6/site-packages (from cryptography) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.12->cryptography) (2.21)
 

2022/09/22 12:30:27 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:30:27 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install prettytable  -i https://pypi.org/simple
2022/09/22 12:30:28 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: prettytable in /usr/local/lib/python3.6/site-packages (2.5.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.6/site-packages (from prettytable) (4.8.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (from prettytable) (0.2.5)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/site-packages (from importlib-metadata->prettytable) (3.6.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.6/site-packages (from importlib-metadata->prettytable) (4.1.1)
 

2022/09/22 12:30:28 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:30:28 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install pynacl  -i https://pypi.org/simple
2022/09/22 12:30:29 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: pynacl in /usr/local/lib64/python3.6/site-packages/PyNaCl-1.5.0-py3.6-linux-x86_64.egg (1.5.0)
Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib64/python3.6/site-packages (from pynacl) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.4.1->pynacl) (2.21)
 

2022/09/22 12:30:29 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:30:30 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install paramiko  -i https://pypi.org/simple
2022/09/22 12:30:30 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: paramiko in /usr/local/lib/python3.6/site-packages (2.11.0)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from paramiko) (1.11.0)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib64/python3.6/site-packages/PyNaCl-1.5.0-py3.6-linux-x86_64.egg (from paramiko) (1.5.0)
Requirement already satisfied: cryptography>=2.5 in /usr/local/lib64/python3.6/site-packages (from paramiko) (38.0.1)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib64/python3.6/site-packages (from paramiko) (4.0.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib64/python3.6/site-packages (from cryptography>=2.5->paramiko) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.12->cryptography>=2.5->paramiko) (2.21)
 

2022/09/22 12:30:30 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:30:31 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; pip install scp  -i https://pypi.org/simple
2022/09/22 12:30:31 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: scp in /usr/local/lib/python3.6/site-packages (0.14.4)
Requirement already satisfied: paramiko in /usr/local/lib/python3.6/site-packages (from scp) (2.11.0)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from paramiko->scp) (1.11.0)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib64/python3.6/site-packages (from paramiko->scp) (4.0.0)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib64/python3.6/site-packages/PyNaCl-1.5.0-py3.6-linux-x86_64.egg (from paramiko->scp) (1.5.0)
Requirement already satisfied: cryptography>=2.5 in /usr/local/lib64/python3.6/site-packages (from paramiko->scp) (38.0.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib64/python3.6/site-packages (from cryptography>=2.5->paramiko->scp) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.12->cryptography>=2.5->paramiko->scp) (2.21)
 

2022/09/22 12:30:31 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

